### ISSUE TITLE
TemplateSyntaxError at /pin/ (humanize)

### ISSUE THREAD

**Issue by wd5** [vchakoshy/django-pin#2]
TemplateSyntaxError at /pin/

'humanize' is not a valid tag library: Template library humanize not found, tried django.templatetags.humanize,django.contrib.staticfiles.templatetags.humanize,django.contrib.admin.templatetags.humanize,pin.templatetags.humanize

Request Method:     GET
Request URL:    http://127.0.0.1:8000/pin/
Django Version:     1.4.1
Exception Type:     TemplateSyntaxError
Exception Value:    

'humanize' is not a valid tag library: Template library humanize not found, tried django.templatetags.humanize,django.contrib.staticfiles.templatetags.humanize,django.contrib.admin.templatetags.humanize,pin.templatetags.humanize

Exception Location:     /usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py in load, line 1043
Python Executable:  /usr/bin/python
Python Version:     2.7.3

In template /usr/local/lib/python2.7/dist-packages/pin/templates/pin/_items.html, error at line 2
'humanize' is not a valid tag library: Template library humanize not found, tried django.templatetags.humanize,django.contrib.staticfiles.templatetags.humanize,django.contrib.admin.templatetags.humanize,pin.templatetags.humanize
1   {% load pin_tags%}
2   {% load humanize %}
3   {% load thumbnail %}
4   {% load daddy_avatar%}
5  
6   {% spaceless %}
7   {% for item in latest_items %}
8  
9   <div class="feed-item" >
10  {% thumbnail item.image "192" as im %}
11  <div class="img-block" style="height: {{im.height}}px; width: {{im.width}}px">
12  <a class="pin-item-link" href="{% url pin-item item.id%}">

**Comment by wd5** [comment]
FIX: To activate these filters, add 'django.contrib.humanize' to your INSTALLED_APPS setting. Once you’ve done that, use {% load humanize %} in a template, and you’ll have access to the following filters.

**Comment by vchakoshy** [comment]
i add this line to installation documentation, w8 for push
